version: "3"

services: 
    webapp:
        build: .
        image: flask
        environment: 
            - FLASK_ENV=development
            - FLASK_APP=app.py
        ports: 
            - 5000:5000

    redis:
        image: redis


